# -*- coding: utf-8 -*-
"""simple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ifVSi3PIS0K08FV-IGjfgFlTRrxGDgz

# Simple Linear Regression

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset=pd.read_csv('Salary_Data.csv')
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.02,random_state=0)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

"""## Predicting the Test set results"""

print(model.predict(x_test))

"""## Visualising the Training set and Test set results"""

plt.scatter(x_train,y_train,color='green')
plt.scatter(x_test,y_test,color='red')
plt.plot(x_train,model.predict(x_train),color='blue')
plt.title('Salary Vs Year of Experiance')
plt.xlabel('Years of Experiance')
plt.ylabel('Salary')
plt.show()

print("Enter The Year Of Experience in any Company")
print(model.predict([[int(input())]]))